[package]
name = "verity-move-oracles"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }

[addresses]
std = "0x1"
verity = "0x42"
verity_test_foreign_module = "0x43"