version: '3.8'

services:
  postgres_db:
    image: postgres:16
    hostname: postgres
    restart: always
    container_name: verity-move-postgres2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - verify-network2
    volumes:
      - postgres-db-data2:/var/lib/postgresql/data

  orchestrator:
    build: 
      dockerfile: ./orch.dockerfile
      context: .
    image: orchestrator2:move
    container_name: verity-move-orchestrator2
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - verify-network2
    depends_on:
      postgres_db:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma migrate deploy &&
        pnpm run start
      "

volumes:
  postgres-db-data2:

networks:
  verify-network2:
    driver: bridge
